# need to make sure that mariadb(1) then wordpress(2) then nginx(3) is done in that order.

#########################################
#		            SERVICES    		        #
#########################################
services:
# ── MARIADB ───────────────────────────────────────────────────
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    networks:
      -  docker-network
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      # test: ["CMD-SHELL", "mysqladmin -u health -psecretphrase ping --silent"]
      test: ["CMD-SHELL", "mysqladmin --defaults-extra-file=/etc/mysql/health.cnf ping --silent"]
      # test: ["CMD-SHELL", "mysqladmin ping --socket=/run/mysqld/mysql.sock --silent"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pw
      - MYSQL_PASSWORD_FILE=/run/secrets/db_user_pw
    secrets:
      - db_root_pw
      - db_user_pw
    restart: unless-stopped

# ── WORDPRESS ──────
  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    networks:
      - docker-network
    volumes:
      - wp-data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DOMAIN_NAME="${LOGIN}.42.fr"
      - WP_TITLE=${WP_PAGE_TITLE}
      - WP_ADMIN_USER_ENV=${WP_ADMIN_USER_ENV}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_ADMIN_PASSWORD_FILE=/run/secrets/credentials
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_user_pw
    secrets:
      - db_user_pw
      - credentials
    restart: unless-stopped

# ── NGINX ───────────────────────────────────────────────────────
  nginx:
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    networks:
      - docker-network
    volumes:
      - type: volume
        source: wp-data
        target: /var/www/html
        read-only: true
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME="${LOGIN}.42"
    depends_on:
      - wordpress
    restart: unless-stopped


#########################################
#              VOLUMES                  #
#########################################
volumes:
  mariadb-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/${LOGIN}/data/mariadb
  wp-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/${LOGIN}/data/wordpress

#########################################
#              NETWORKS                 #
#########################################
networks:
  docker-network:
    driver: bridge


#########################################
#              SECRETS                  #
#########################################
secrets:
  db_root_pw:
    file: ../secrets/db_root_password.txt

  db_user_pw:
    file: ../secrets/db_password.txt

  credentials:
    file: ../secrets/credentials.txt